### ISSUE TITLE
对本项目 wiki 页面 CSV文件 内容的一些修订

### ISSUE THREAD

**Issue by AtmoOmen** [Souma-Sumire/FFXIVChnTextPatch-Souma#12]
修订原则:

1. 修订均有资料/游戏内容支撑
2. 尽量采用游戏原文文本
3. 仅对有实际中文文本的文件 (由程序按一定规则自动筛选) 进行了逐一查阅修订
4. 下方大部分条目都是改动过的

修改内容：

- Achievement.csv 成就名
- AchievementCategory.csv 成就分类 (细分)
- AchievementKind.csv 成就种类 (整体)
- Action.csv 技能
- ActionCategory.csv 技能类型
- ActionComboRoute.csv 连击类技能
- Adventure.csv 探索笔记
- Aetheryte.csv 以太之光
- AirshipExplorationParamType.csv 飞空艇数据
- AirshipExplorationPoint.csv 飞空艇探索点
- AnimaWeapon5Param.csv 魂武属性 (加点)
- AnimaWeapon5PatternGroup.csv 魂武水晶砂交换品
- AOZScore.csv 青魔挑战
- AquariumWater.csv 水族箱环境
- BannerBg.csv 肖像背景
- BannerDecoration.csv 肖像装饰
- BannerDesignPreset.csv 肖像预设
- BannerFrame.csv 肖像边框
- BannerTimeline.csv 肖像动作 (不含情感动作)
- BaseParam.csv 角色状态参数
- BeastReputationRank.csv 友好部族等级
- BeastTribe.csv 友好部族
- BuddyAction.csv 陆行鸟(搭档)指令
- BuddyEquip.csv 陆行鸟装备
- CharaCardBase.csv 铭牌底色
- CharaCardDecoration.csv 铭牌花纹
- CharaCardDesignPreset.csv 铭牌预设
- CharaCardHeader.csv 铭牌顶部装饰
- CharaCardPlayStyle.csv 游戏风格 (个人信息)
- ChocoboRaceAbility.csv 陆行鸟竞赛技能
- ChocoboRaceItem.csv 陆行鸟竞赛道具
- CircleActivity.csv 同好会主要活动
- ClassJob.csv 职业
- ClassJobCategory.csv 职业分类
- CollectablesShop.csv 生产肝武商店
- CollectablesShopItemGroup.csv 生产肝武商店分类
- Companion.csv 宠物
- CompanionMove.csv 宠物行动方式
- CompanyAction.csv 部队特效
- CompanyCraftDraft.csv 部队合建设计图
- CompanyCraftDraftCategory.csv 部队合建设计图分类
- CompanyCraftManufactoryState.csv 部队合建品质
- CompanyCraftType.csv 部队合建笔记范围/种类
- CompleteJournal.csv 已完成日志
- ContentFinderCondition.csv 副本名称
- ContentGauge.csv 副本机制量谱
- ContentRoulette.csv 日随副本
- ContentsNote.csv 挑战笔记
- ContentsTutorial.csv 特殊场景探索
- ContentType.csv 副本类型
- CraftAction.csv 生产技能
- CraftType.csv 生产配方类型
- DeepDungeon.csv 深层迷宫
- DeepDungeonEquipment.csv 深层迷宫聚魔装备
- DeepDungeonFloorEffectUI.csv 深层迷宫魔法效果
- DeepDungeonItem.csv 深层迷宫道具
- DeepDungeonMagicStone.csv 深层迷宫魔石
- DpsChallenge.csv 木人挑战
- DynamicEvent.csv 博兹雅/高原CE
- DynamicEventEnemyType.csv 博兹雅/高原CE敌人类型
- Emote.csv 情感动作
- EmoteCategory.csv 情感动作分类
- ENpcResident.csv NPC名称
- EObjName.csv 副本可交互对象名
- EurekaAetherItem.csv 优雷卡以太壶
- EventAction.csv 交互动作
- EventItem.csv 任务道具
- ExtraCommand.csv 特殊命令
- ExVersion.csv 资料片版本名
- FashionCheckThemeCategory.csv 时尚品鉴装备关键词
- FashionCheckWeeklyTheme.csv 时尚品鉴主题
- Fate.csv 临危受命
- FCActivityCategory.csv 部队动态类型
- FCAuthority.csv 部队阶级权限
- FCAuthorityCategory.csv 部队阶级权限设置类别
- FCChestName.csv 部队箱 (?)
- FccShop.csv 部队战绩交易
- FCHierarchy.csv 部队阶级
- FCProfile.csv 部队主要活动
- FCReputation.csv 部队所属军队友好关系等级
- FCRights.csv 部队功能
- FieldMarker.csv 场景标记
- GatheringPointName.csv 采集点名称
- GatheringType.csv 采集点类型
- GcArmyExpedition.csv 冒险者分队任务
- GcArmyExpeditionType.csv 冒险者分队任务类型
- GcArmyTraining.csv 冒险者分队训练
- GCRankGridaniaFemaleText.csv 双蛇党军衔名 (女)
- GCRankGridaniaMaleText.csv 双蛇党军衔名 (男)
- GCRankLimsaFemaleText.csv 黑涡团军衔名 (女)
- GCRankLimsaMaleText.csv 黑涡团军衔名 (男)
- GCRankUldahFemaleText.csv 恒辉队军衔名 (女)
- GCRankUldahMaleText.csv 恒辉队军衔名 (男)
- GCShopItemCategory.csv 军队商店物品类型
- GeneralAction.csv 共通技能
- GilShop.csv 金币商店类别
- GrandCompany.csv 所属大国防联军
- GroupPoseStamp.csv 集体动作装饰/边框
- GroupPoseStampCategory.csv 集体动作装饰/边框分类
- GuardianDeity.csv 守护神
- HousingPreset.csv 房屋预设
- HowTo.csv 新手指南
- HWDAnnounce.csv 伊修加德重建公告
- HWDCrafterSupplyTerm.csv 生产物品重建计划期数
- HWDGathereInspectTerm.csv 采集物品重建计划期数
- IKDRoute.csv 海钓航线
- InclusionShopCategory.csv 工票交易类别
- Item.csv 道具
- ItemSearchCategory.csv 道具搜索分类
- ItemSeries.csv 道具系列
- ItemSpecialBonus.csv 道具套装效果
- ItemUICategory.csv 道具分类
- JournalCategory.csv 任务日志分类 (大)
- JournalGenre.csv 任务日志分类 (小)
- JournalSection.csv 任务日志大类 (最大)
- Leve.csv 理符
- LeveAssignmentType.csv 理符递交类型
- LeveClient.csv 理符任务发布人
- LogFilter.csv 消息筛选
- MainCommand.csv 快捷指令
- MainCommandCategory.csv 快捷命令类别
- Marker.csv 目标标记
- McGuffinUIData.csv 重要物品
- MinionRace.csv 萌宠之王宠物类型
- MinionSkillType.csv 萌宠之王宠物技能类型
- MJICraftworksObjectTheme.csv 无人岛工坊物品类别
- MJIHudMode.csv 无人岛行动模式
- MJIItemCategory.csv 无人岛物品类别
- MJIName.csv 无人岛地区名
- MonsterNote.csv 讨伐笔记
- Mount.csv 坐骑
- MYCTemporaryItemUICategory.csv 失传技能库类别
- MYCWarResultNotebook.csv 战果记录
- NotebookDivision.csv 制作笔记分区
- NotebookDivisionCategory.csv 制作笔记分类
- OnlineStatus.csv 在线状态
- OpenContentCandidateName.csv 异国的诗人
- Orchestrion.csv 乐谱
- OrchestrionCategory.csv 乐谱分类
- Ornament.csv 时尚配饰
- Pet.csv 召唤兽
- PetAction.csv 召唤兽技能
- PetMirage.csv 召唤兽投影
- PlaceName.csv 地名
- PublicContent.csv 永结同心
- Quest.csv 任务
- QuestRewardOther.csv 任务特殊奖励
- RacingChocoboNameCategory.csv 竞赛陆行鸟名称
- RacingChocoboParam.csv 竞赛陆行鸟属性
- RetainerTaskRandom.csv 雇员探索委托
- SecretRecipeBook.csv 秘籍
- SnipeTalkName.csv 任务的狙击小游戏
- SpecialShop.csv 特殊兑换物商店
- Stain.csv 染剂
- Status.csv 状态
- SubmarineMap.csv 潜水艇海图
- TopicSelect.csv 特殊道具交易
- Town.csv 雇员登记市场
- Trait.csv 特性
- TripleTriadCard.csv 九宫幻卡
- TripleTriadCardType.csv 九宫幻卡类型
- TripleTriadCompetition.csv 九宫幻卡大赛
- TripleTriadRule.csv 九宫幻卡规则
- VVDNotebookContents.csv 多变迷宫故事
- VVDNotebookSeries.csv 多变迷宫系列
- Warp.csv 副本外场景传送点
- Weather.csv 天气

**Comment by Souma-Sumire** [comment]
感谢提供！

**Comment by Souma-Sumire** [comment]
已合并
