### ISSUE TITLE
70级的主线任务有一处没有翻译

### ISSUE THREAD

**Issue by kanzakiken** [Souma-Sumire/FFXIVChnTextPatch-Souma#16]
主线任务名:废王的黄金
概要和部分剧情没有翻译
![70级主线-1](https://github.com/Souma-Sumire/FFXIVChnTextPatch-Souma/assets/18526398/62e743f0-6ed8-4103-ad07-f5b1c7bb3a63)
![70级主线-2](https://github.com/Souma-Sumire/FFXIVChnTextPatch-Souma/assets/18526398/03d1c896-1cf1-462a-a282-e71f9c6efe69)

**Comment by Souma-Sumire** [comment]
任务文本是自动化处理的 空的都是国服没有的

这个任务在国际服6.5进行了改动（文本ID变化）

所以表现为没翻译

**Comment by kanzakiken** [comment]
> 任务文本是自动化处理的 空的都是国服没有的
> 
> 这个任务在国际服6.5进行了改动（文本ID变化）
> 
> 所以表现为没翻译

原来如此
