### ISSUE TITLE
使用补丁后会出现dx11报错

### ISSUE THREAD

**Issue by NTnarasha** [Souma-Sumire/FFXIVChnTextPatch-Souma#2]
![image](https://user-images.githubusercontent.com/58031155/219906525-55a24cc4-42a0-4985-ad60-8f5f4e3c1a0f.png)

**Comment by Souma-Sumire** [comment]
请提供复现步骤

**Comment by NTnarasha** [comment]
![image](https://user-images.githubusercontent.com/58031155/219909041-12dd11d1-b0d8-4eef-af26-2847d36f7f25.png)
![image](https://user-images.githubusercontent.com/58031155/219909076-b6431486-b742-4c1c-a87e-a8332b8b81b2.png)
![image](https://user-images.githubusercontent.com/58031155/219909091-9299915a-e03f-4e11-82a1-574def68bc0d.png)
![image](https://user-images.githubusercontent.com/58031155/219909103-45419a12-fa17-49be-a34d-3f0bc750d496.png)
![image](https://user-images.githubusercontent.com/58031155/219909109-1209d353-a33a-4cf8-a7b1-0a31c9f3f5d3.png)
![image](https://user-images.githubusercontent.com/58031155/219909118-fe991333-228d-4c09-a71f-2f96ca263298.png)
![image](https://user-images.githubusercontent.com/58031155/219909132-7b8ab4c5-1905-4fbf-963b-8ef450904ef0.png)
正常

**Comment by NTnarasha** [comment]
![image](https://user-images.githubusercontent.com/58031155/219909166-108ec6fa-70ec-4b20-aac8-27a0639f02c9.png)
![image](https://user-images.githubusercontent.com/58031155/219909182-8f73ea31-28fd-4220-9bc4-8532fbfee9dd.png)
![image](https://user-images.githubusercontent.com/58031155/219909210-14dee3f8-7f0c-4d86-97a3-83442a514bed.png)

**Comment by NTnarasha** [comment]
![image](https://user-images.githubusercontent.com/58031155/219909247-2ee6a8e5-ef78-488c-840c-8972a4e20116.png)
![image](https://user-images.githubusercontent.com/58031155/219909267-19aff310-c918-4ebf-a835-07e3581b9cdb.png)
![image](https://user-images.githubusercontent.com/58031155/219909287-2983db61-bf00-48e3-a9f1-36ef417b41f9.png)

**Comment by Souma-Sumire** [comment]
是否按要求开启了4k贴图

**Comment by NTnarasha** [comment]
![image](https://user-images.githubusercontent.com/58031155/219916203-5447890e-873e-4a15-9cd8-0dc78ca04a29.png)
替换之后
![image](https://user-images.githubusercontent.com/58031155/219916389-9ba3a766-e889-4d14-9eb5-92a94e5cf639.png)

**Comment by NTnarasha** [comment]
已解决操作的界面不对
