### ISSUE TITLE
6.57 由于没借到号 暂时无法更新

### ISSUE THREAD

**Issue by Souma-Sumire** [Souma-Sumire/FFXIVChnTextPatch-Souma#20]
![~$EBB@D8E``B4FKADTY%PM](https://github.com/Souma-Sumire/FFXIVChnTextPatch-Souma/assets/33572696/a810c21e-a2fd-4c4d-a903-8df3019d485e)

**Comment by liuxd17thu** [comment]
我这边可以借，怎么联系（？

**Comment by Souma-Sumire** [comment]
> 我这边可以借，怎么联系（？

QQ `553469159 ` =3=
