### ISSUE TITLE
penumbra导入汉化pmp时进度越界无法结束

### ISSUE THREAD

**Issue by IbukiFuko** [Souma-Sumire/FFXIVChnTextPatch-Souma#24]
### 描述

penumbra导入 Chinese Text Mod (6.58 Hotfix1) v1.0.3.pmp 时，进度最终显示13137/13136，一直处于等待状态。此时mod列表中已经出现导入的mod，可以点击cancel手动关闭界面。导入 ChnAXIS.pmp 时正常。

### 附加详情/重现步骤

导入Chinese Text Mod (6.58 Hotfix1) v1.0.3.pmp并等待进度更新

### 配置信息

6.58 hotfix1 003

### 日志和截图

![image](https://github.com/Souma-Sumire/FFXIVChnTextPatch-Souma/assets/44281408/f865a8f4-cf15-4b17-a347-2c89e2c70944)

### 确认

- [X] 我已经审阅了<a href='/Souma-Sumire/FFXIVChnTextPatch-Souma?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E8%A7%A3%E7%AD%94qa'>常见问题解答</a>，并验证了我的设置是正确的。
- [X] 我使用了搜索功能确认此问题是否已经存在。

**Comment by Souma-Sumire** [comment]
嗯……我也不知道为什么……

**Comment by Souma-Sumire** [comment]
经过测试，初步结论是：
- 超出索引并不是问题，更换更小体积的Mod，注意观察最后的数字，发现即使超出索引也可以成功导入的。
- 现在卡在了 Deduplicating（去重）环节，可能是因为文件数过于庞大，所以校验程序跑的非常慢（指数级灾难），等很久很久之后他会跑完。

## 解决方案
1. 让用户等
2. 让用户手动点 close
3. 想办法减少 Mod 的文件数量
4. 想办法跳过 Deduplicating
