### ISSUE TITLE
进博兹雅对话卡死

### ISSUE THREAD

**Issue by sunamercuri** [Souma-Sumire/FFXIVChnTextPatch-Souma#29]
### 描述

和进博兹雅的NPC对话的时候会无法弹出对话框

### 附加详情/重现步骤

和进博兹雅的NPC对话，对话框无法弹出，但游戏仍能运行，会卡死在对话中只能强退

### 配置信息

V2.1.1 7.0第二版

### 确认

- [X] 我已经审阅了<a href='/Souma-Sumire/FFXIVChnTextPatch-Souma?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E8%A7%A3%E7%AD%94qa'>常见问题解答</a>，并验证了我的设置是正确的。
- [X] 我使用了搜索功能确认此问题是否已经存在。

**Comment by Souma-Sumire** [comment]
请尝试 v2.1.2 第三版汉化，应该修复了。（我没开bzy无法测试）

**Comment by sunamercuri** [comment]
确认了，已经修复了
