### ISSUE TITLE
生产和采集职业的90级以后的职业特性描述内容为“0”

### ISSUE THREAD

**Issue by kanzakiken** [Souma-Sumire/FFXIVChnTextPatch-Souma#30]
### 描述

技能描述错误

### 附加详情/重现步骤

如截图所示，测试所有采集和生产职业的90级之后的职业特性描述，内容错误

### 配置信息

使用最新版汉化包7.0-003-overwrite

### 日志和截图

以下是打了汉化包的截图
![QQ截图20240629145629](https://github.com/Souma-Sumire/FFXIVChnTextPatch-Souma/assets/18526398/809019e9-7e53-4c7a-a56e-2af9b8cc7e3f)
![QQ截图20240629145546](https://github.com/Souma-Sumire/FFXIVChnTextPatch-Souma/assets/18526398/744591bb-ef94-4bb8-b73d-b3a4467ab544)
![QQ截图20240629145531](https://github.com/Souma-Sumire/FFXIVChnTextPatch-Souma/assets/18526398/b3b55e49-796f-4f6a-8d20-582248e28e40)
以下是未打汉化包的截图
![{5970C822-DF98-D43C-3B67-445D6AAA551F}](https://github.com/Souma-Sumire/FFXIVChnTextPatch-Souma/assets/18526398/9ee56d6e-58dc-4d99-9ece-a51219c59bf1)

### 确认

- [X] 我已经审阅了<a href='/Souma-Sumire/FFXIVChnTextPatch-Souma?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E8%A7%A3%E7%AD%94qa'>常见问题解答</a>，并验证了我的设置是正确的。
- [X] 我使用了搜索功能确认此问题是否已经存在。

**Comment by Souma-Sumire** [comment]
Excel拉Vlookup之后忘记把0替换掉了（ 
预计于 7.0 004 修复
