### ISSUE TITLE
希望可以汉化BOSS和小怪名称，或者增加汉化的选项

### ISSUE THREAD

**Issue by bright-detsu** [Souma-Sumire/FFXIVChnTextPatch-Souma#32]

**Comment by bright-detsu** [comment]
希望可以汉化BOSS和小怪名称，或者增加BOSS 怪物名称的汉化CSV文件，自行工具进行汉化

**Comment by Small-Dianer** [comment]
汉化怪物名称会导致无法使用 cactbot
如果没有 cactbot 使用的需求，可以考虑使用 GP 版的汉化

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Brightです ***@***.***>
发送时间: Saturday, July 6, 2024 12:25:05 PM
收件人: Souma-Sumire/FFXIVChnTextPatch-Souma ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [Souma-Sumire/FFXIVChnTextPatch-Souma] 希望可以汉化BOSS和小怪名称，或者增加汉化的选项 (Issue #32)


希望可以汉化BOSS和小怪名称，或者增加BOSS 怪物名称的汉化CSV文件，自行工具进行汉化

―

**Comment by Souma-Sumire** [comment]
由于引入BnpcName会为项目增加较多复杂度，因此没有提供的计划。你可以自行替换gp的该文件。
