### ISSUE TITLE
ActionTransient.csv 鐮刀小錯誤

### ISSUE THREAD

**Issue by Liteya** [Souma-Sumire/FFXIVChnTextPatch-Souma#38]
### 描述

翻譯錯誤

### 详细描述

resource/rawexd/ActionTransient.csv
縊殺行刑 敘述
36971  背面 (內文寫成側面)
https://jp.finalfantasyxiv.com/jobguide/reaper/

### 确认

- [X] 我已经确认了文本翻译是否准确，并且确定问题确实存在。
- [X] 我已经搜索了现有的错误报告，以确保我没有重复提交相同的问题。

**Comment by Souma-Sumire** [comment]
感谢回报 下个版本修正
