### ISSUE TITLE
武士的回返

### ISSUE THREAD

**Issue by jc-ff14** [Souma-Sumire/FFXIVChnTextPatch-Souma#39]
### 描述

7.0的武士居合術無法正常出現"回返啟動"

### 附加详情/重现步骤

(原本是出現在7.01版本中的問題, 最新的 7.05 版本未測試)

武士使用居合術之後, 無法正常出現"回返啟動"(例如天下五劍, 雪月花...)

個人判斷是"回返的BUFF, 並未進行翻譯, 導致觸發機制沒有啟動"

### 配置信息

7.01

### 确认

- [X] 我已经审阅了<a href='/Souma-Sumire/FFXIVChnTextPatch-Souma?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E8%A7%A3%E7%AD%94qa'>常见问题解答</a>，并验证了我的设置是正确的。
- [X] 我使用了搜索功能确认此问题是否已经存在。

**Comment by Souma-Sumire** [comment]
pre-release的问题

**Comment by jc-ff14** [comment]
所以請問目前7.05版本已解決這個問題了嗎?

**Comment by Souma-Sumire** [comment]
你是否确定是7.01游戏版本使用7.01汉化发行版，因为我从未遇到过。

**Comment by Souma-Sumire** [comment]
理论上只会在7.05客户端使用7.01或以前的csv进行汉化器汉化才会出现该问题

**Comment by Souma-Sumire** [comment]
總之現在是沒有問題的（我說簡體中文你可以看懂嗎？）

**Comment by jc-ff14** [comment]
沒問題 我可以看得懂簡體的^^

**Comment by jc-ff14** [comment]
你還特地用繁體寫給我看 太貼心了! 謝謝您!!
