### ISSUE TITLE
可以在 cvs 中预留怪物名称的翻译文件吗？

### ISSUE THREAD

**Issue by EXWhiteDragon** [Souma-Sumire/FFXIVChnTextPatch-Souma#42]
我个人不在乎 Cactbot Raidboss，只是想保证外语能力不太强的直接入坑国际服朋友也能看懂怪物名，并从中享受到与名称相关的故事背景和剧情。

原本在 27 号之前，cvs 全选汉化是能汉化怪物名的，我也一直是这样使用的。当在 27 日更新后，即便我 pull 了最新版本，通过汉化器「全选汉化范围」，发现怪物名称仍旧没被汉化，就像是自 27 日后就受到了影响。

我理解您的用意，不过汉化工具本身就有选择汉化范围的功能。备一份怪物名称的文件，就算是考虑到需要使用 Cactbot Raidboss 的朋友，既然都是可选了，完全也可以满足所有人的需要吧。

也可能是单纯版本更新后，怪物 ID 变化旧名称汉化失效了，而不是您彻底移除了怪物名称文件？我也不太懂，只是希望能解决这个问题，谢谢您的帮助！

**Comment by Souma-Sumire** [comment]
你好

> 原本在 27 号之前，cvs 全选汉化是能汉化怪物名的，我也一直是这样使用的。当在 27 日更新后，即便我 pull 了最新版本，通过汉化器「全选汉化范围」，发现怪物名称仍旧没被汉化，就像是自 27 日后就受到了影响。

本项目维护至今，从未提供过怪物名称的汉化，你可能是使用的gp的版本

> 我理解您的用意，不过汉化工具本身就有选择汉化范围的功能。备一份怪物名称的文件，就算是考虑到需要使用 Cactbot Raidboss 的朋友，既然都是可选了，完全也可以满足所有人的需要吧。

我个人希望项目保持简单，所以不会为了小部分用户的需求，而为所有用户带来一些额外的操作
（需要额外的文档说明（本身文档就很繁琐了）、对用户增添了额外的心智负担、使得点击全选按钮成为了有风险的一件事等）

这些操作应当由有需求的用户承担（比如您）：

- 手动将 `resource\options\BnpcName.csv` （目前仅包含国服已有的文本）放置至 `resource\rawexd` 文件夹中，随后使用汉化器进行汉化

（此回复发送后，将首次添加怪物名称文件）
