### ISSUE TITLE
7.1更新后，如果打7.05版本的补丁，会在主线到达遗产之地的时候造成游戏闪退，在后续更新时请注意修复

### ISSUE THREAD

**Issue by bright-detsu** [Souma-Sumire/FFXIVChnTextPatch-Souma#44]
### 描述

7.1更新后，如果打7.05版本的补丁，会在主线到达遗产之地的时候造成游戏闪退，在后续更新时请注意修复

### 附加详情/重现步骤

7.1更新后，如果打7.05版本的补丁，会在主线到达遗产之地的时候造成游戏闪退，在后续更新时请注意修复

### 配置信息

XXX

### 确认

- [X] 我已经审阅了<a href='/Souma-Sumire/FFXIVChnTextPatch-Souma?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E8%A7%A3%E7%AD%94qa'>常见问题解答</a>，并验证了我的设置是正确的。
- [X] 我使用了搜索功能确认此问题是否已经存在。

**Comment by flycatki** [comment]
昨天发现临时打7.05版本的补丁，只是为了做以前的主线，现在到3.0，但是有其启动的时候还没有到登录页就出了一个directx11的什么错误后就奔溃了，还原成原游戏文件是没问题的，这个临时有兼容的办法么，多谢
