### ISSUE TITLE
国际服更新6.4之后剧情的中文全部没了

### ISSUE THREAD

**Issue by chenjuntu** [Souma-Sumire/FFXIVChnTextPatch-Souma#5]
国际服在上周更新6.4之后，感谢作者在第一时间就推出了适配6.4的中文补丁，但是有个问题就是剧情对话的汉化全部都没了（仅仅在有配音的cutscene字幕是中文）。我是回归玩家，所以还在爬剧情，按理说6.0的剧情中文应该在之前就存在了的，不应该全部消失了才对的呀？我还远远没有到最新的6.4剧情，不存在说汉化组还没有汉化到的情况。
我尝试过使用了还原补丁然后再重新安装汉化，但是没有用。我朋友是升级到6.4后才第一次安装的，也发现没有剧情汉化。不知道是什么原因呢？

**Comment by Souma-Sumire** [comment]
剧情有大量改动，没有时间做适配，强行打旧文件会出问题，所以删除。
