### ISSUE TITLE
大佬能不能还像以前一样github的release里也放一下

### ISSUE THREAD

**Issue by superjump22** [Souma-Sumire/FFXIVChnTextPatch-Souma#6]
今天不知道咋了，网盘比github还慢

**Comment by Souma-Sumire** [comment]
你是不是开代理了。

（我上传也很慢啊好麻烦）

或者你可以自己用csv汉化一下， 用gp的汉化器。csv换成我的

**Comment by superjump22** [comment]
没有开代理，我一开始也以为是这个原因，然后关了重新下还是一样，甚至开了代理还快一点

**Comment by Souma-Sumire** [comment]
release还是太麻烦了，实在不行QQ群文件下吧。

**Comment by superjump22** [comment]
> release还是太麻烦了，实在不行QQ群文件下吧。

好的，没事我慢慢下吧，但是009今天下载404
