### ISSUE TITLE
大水晶的“取消”似乎翻译对应错了

### ISSUE THREAD

**Issue by superjump22** [Souma-Sumire/FFXIVChnTextPatch-Souma#8]
[![2.png](https://i.postimg.cc/wvHBDS1k/2.png)](https://postimg.cc/06WxsXd6)

[![1.png](https://i.postimg.cc/283SddSg/1.png)](https://postimg.cc/8jQGN6Wb)

**Comment by Souma-Sumire** [comment]
自动化没判断好，有一些文本串行了
